# Exception to indicate that a dependent class was called during a unit test.
class DependendClassCallDuringUnitTestException(Exception):
    pass
